const quizData = [
  {
    phase: 1,
    name: "Phase 1 (Cutubka 1aad & 2aad)",
    chapters: [
      {
        title: "Cutubka 1aad : Waxbarashada caafimaadka",
        questions: [
          { q: "Waa maxay cudurada la is qaadsiiyo ?", a: "Waa cudur kasto oo kasoo gudba qof qaba una gudbi kara qof aan qabin." },
          { q: "Waa maxay soore ?", a: "Soore waa martigaliyaha cudurka." },
          { q: "Sheeg siyaabaha lagu kala Qaado Cudurka ?", a: "Hawada , Biyaha , Cuntada , Galmada , iyo Cayayaanka." },
          { q: "Maxaa kamid ah cudurada ku faafa hawada ?", a: "Hargabka , Boronkiitada , iyo Tiibishada." },
          { q: "Sheeg cudurada lagu kala qaado galmada ?", a: "Waraabowga (isfiilitada) , Jabtada , iyo Aydhiska." },
          { q: "Sidee lagu kala qaadaa tiifowga iyo daacuunka ?", a: "Biyaha iyo Cuntada wasakhaysan." },
          { q: "Waa Maxay Duumo (Malaariyo) ?", a: "Waa cudur halis ah waxa ayna kamid tahay xanuunada faafa ee la isqaadsiiyo." },
          { q: "Yaa keena cudurka duumada ?", a: "Waxaa keena Cayayaanka." },
          { q: "Waa maxay deris kunoole ?", a: "Waa noole ku dul nool noole kale." },
          { q: "Waa maxay fansidar ?", a: "Waa daawada ka hortaga cudurka duumada." },
          { q: "Magacoow jeermiga sababa cudurka duumada ?", a: "PLASMODIUM (BALAASMOODIYAM)." },
          { q: "Sheeg noocyada balaasmoodiyam?", a: "Balaasmoodiyam falsibaram , Balaasmoodiyam fiifakis , Balaasmoodiyam ofeli , Balaasmoodiyam malaariyo." },
          { q: "Yaa faafiya cudurka duumada ?", a: "Kaneecada dhediga ee loo yaqaano ANOPHELES (ANOOFALIS)." },
          { q: "Xagee ayay weerartaa duumada ?", a: "Unugyada beerka iyo unugyada cascas ee dhiiga." },
          { q: "Sheeg calaamadaha lagu garto cudurka duumada ?", a: "Qandho , beer yarada oo bararta , gariir , matag , afka oo qaraar noqda , murqo xanuun , dhiig yaraan daal badan , tabar darro iyo dhidid." },
          { q: "Sheeg dadka unugul cudurka duumdada ?", a: "Carruurta da’dooda ka yartahay 5 sano iyo haweenka uurka leh." },
          { q: "Xagee ayey kunooshahay anoofalis ?", a: "Meelaha qabatinta musqulaha iyo wabiyada." },
          { q: "Sheeg siyaabaha ay ku gudubto duumada ?", a: "Qof qaba duumada oo dhiig laga shubo, Xubnaha oo la'iskugu deeqo, Cirbadaha oo lala wadaago, ama Hooyada uurka leh oo u gudbisa ilmaha." },
          { q: "Sheeg shan kamid ah siyaabaha loogu hortagi karo cudurka duumada ?", a: "In musqulaha kolooriin lagu shubo, in labuufiyo guryaha, in maro kaneeco la xerto, in fansidar loogu hortago, iyo in labuufiyo xaafadaha." },
          { q: "Waa maxay galmo ?", a: "Waa isku taga labka iyo dhediga." },
          { q: "Maxaa sababa cudurka waraabowga ( Isfiilitada) ?", a: "Waxaa sababta bakteeriyada (Tarebanema Balidam)." },
          { q: "Sheeg heerarka uu maro waraabowga ( Isfiilatada) ?", a: "Waxa uu maraa 3 heer." },
          { q: "Sheeg calaamadaha uu ku bilaawdo waraabowga heerkiis 1aad ?", a: "Boogo yar aan xanuun laheyn oo kasoo baxa agagaarka xubnaha taranka, afka iyo malawadka (qaataa 3 ilaa 8 todobaad)." },
          { q: "Xagee ayay nabarada kasoo baxaan heerka 2aad ee cudurka waraabowga ?", a: "Waxey kasoo baxaan calaacasha iyo cagta (qaadan karaa 2 ilaa 12 todobaad)." },
          { q: "Sheeg calaamadaha waraabowga lagu garto heerka 2aad ?", a: "Qandho , murqo xanuun , cuna xanuun , tabardaro , iyo daal." },
          { q: "Maxaa lagu daweeyaa cudurka waraabowga ?", a: "ANTIBIOTICS ( ANTIBAAYOOTIKIS)." },
          { q: "Xagee ayuu ku dhacaa cudurka waraabowga heerkiis 3aad ?", a: "Wadnaha , xididada jirka , maskaxda , beerka , lafaha iyo kalagoysyada." },
          { q: "Muxuu keenaa cudurka waraabowga heerkiis 3aad ?", a: "Naafanimo , dhimasho iyo waali." },
          { q: "Sidee lagu xakameynayaa cudurka waraabowga ?", a: "In laga fogaado sinada." },
          { q: "Waa maxay jabto ?", a: "Jabto waa caabuq lagu kala qaado galmada." },
          { q: "Maxaa loo yaqaanaa Bakteeriyada sababa jabtada ?", a: "Bakteeriyada neyseeriya gonoriya." },
          { q: "Xagee ayey jabtada kaga dhacdaa raga ?", a: "Waxey kaga dhacdaa kaadi mareenka." },
          { q: "Xagee ayey jabtada kaga dhacdaa dumarka ?", a: "Waxa ay kaga dhacdaa qeybta hore ee ilmo galeenka iyo marinka kaadida." },
          { q: "Sheeg halka ay saameyso cudurka jabtada ?", a: "Waxa ay saameysaa malawadka , futada , cunaha iyo miskaha." },
          { q: "Maxay sababi kartaa jabtada hadii aan laga daaweynin bukaanka ?", a: "Waxey keeni kartaa xaalad caafimaad daro aad halis u ah." },
          { q: "Sheeg shan kamid ah astaamaha kamuuqda raga jabtada qaba ?", a: "Kaadida oo badata, cunaha oo xanuuna, barar ama xanuun xaniinyaha, xanuun ama gubasho xilliga kaadida, iyo kalagoysyada oo casaada." },
          { q: "Sheeg shan kamid ah astaamaha kamuuqda dumarka jabtada qaba ?", a: "Qandho, madhalaysnimo, cunaha oo xanuuna, dhiig yimaada xiliga caadada kahor, iyo kaadida oo badata." },
          { q: "Immisa maalmood ayaa lagu ogaan karaa jabtada ?", a: "Waxaa lagu ogaan karaa ugu yaraan 14 maalmood." },
          { q: "Maxaa lagu daaweeyaa jabtada ?", a: "Waxaa lagu daaweeyaa jeermis dilayaasha ( ANTIBIOTICS)." },
          { q: "Sidee lagu xakameyn karaa jabtada ?", a: "In laga fogaado sinada." },
          { q: "Waa maxay aydhis ?", a: "Aydhis waa cudur dilaa ah." },
          { q: "Maxaa sababa aydhiska ?", a: "Waxaa sababa fayraska lagu magacaabo (HIV)." },
          { q: "Maxaa laga soo gaabiyay ereyga HIV ?", a: "Human immune deficiency virus." },
          { q: "Waa maxay micnaha erayga HIV ?", a: "Waa fayrus difaaca aadamiga yareeya." },
          { q: "Maxaa laga asoo gabiyey erayga AIDS ?", a: "Acquired immune deficiency syndrome." },
          { q: "Waa maxay micnaha erayga AIDS ?", a: "Waa caabuqa difaaca aadamiga yareeya." },
          { q: "Sheeg siyaabaha lagu kala qaado aydhiska ?", a: "Hooyada uurka leh, dhiig lagu shubo, xubnaha oo la iskugu deeqo, iyo cirbadaha wadaaga ah." },
          { q: "Sheeg shan kamid ah astaamaha aydhiska ?", a: "Caabuq dhuunta ah , Murqaha oo xanuuna , Qufac qalalan , Shuban mudo dheer socda , Tabardaro." },
          { q: "Sidee lagu xakameyn karaa aydhiska ?", a: "In laga fogaado galmada xaaraanta, lagana fogaado cirbadaha iyo qalabka la wadaago." },
          { q: "Sheeg magaca daawada loo adeegsado aydhiska ?", a: "Aydhiska daawo malahan." },
          { q: "Maxaa loo adeegsadaa daawada ?", a: "Waxaa loo adeegsadaa in lagu daaweeyo cudurada." },
          { q: "Maxay daawadu kabadashaa jirka ?", a: "Waxay kabadashaa sida uu jirka ushaqaynaayo." },
          { q: "Maxay daawadu uleedahay jirka ?", a: "Waxtar iyo waxyeelo." },
          { q: "Waa maxay talo bixinta dhakhtarka ?", a: "Waa qoraal tilmaamaya sida loo adeegsado daawada." },
          { q: "Maxuu tilmaamayaa qoraalka dhakhtarka ?", a: "Wuxuu tilmaamayaa xadiga daawada laga qaadanayo iyo mudada uu adeegsanaayo." },
          { q: "Goormee ay daawadu waxyeelaysaa jirka ?", a: "Marka si qaldan loo adeegsado." },
          { q: "Sheeg sadex kamid ah daawooyinka maskaxda waxyeeleeya ?", a: "Daawooyinka xanuunka suuliya , Daawooyinka keena saqrada , Daawooyinka dajiyayaasha." }
        ]
      },
      {
        title: "Cutubka 2aad : Biyaha",
        questions: [
          { q: "Sheeg qaybaha uu dhulka ka koobanyahay ?", a: "waxa uu ka koobanyahay biyo iyo barri." },
          { q: "Immisa biyo ah dhulka ?", a: "70%" },
          { q: "Immisa barri ah dhulka ?", a: "30%" },
          { q: "Sheeg boqoleyda biyaha dhanaan ee dhulka ?", a: "97%" },
          { q: "Sheeg boqoleyda biyaha macaan ee dhulka ?", a: "1%" },
          { q: "Wan maxay ilaalinta biyaha ?", a: "Ilaalinta biyaha waa beeqaaminta biyaha." },
          { q: "Waa maxay waraab dhibciska ?", a: "Waa buufinta biyaha." },
          { q: "Waa maxay qabashada biyaha ?", a: "waa keydinta biyaha." },
          { q: "Xagee lagu keydiyaa biyaha ?", a: "war iyo balli." },
          { q: "sheeg noocyada waraabka ?", a: "waa laba nooc oo kala ah : waraab dhibcis iyo waraab daad." },
          { q: "Xilligee ugu wanaagsan in la waraabiyo beeraha?", a: "Subaxdii iyo habeenkii ama marka uu qabowga jiro." },
          { q: "Waa maxay dikhowga biyaha ?", a: "waa wasaqeynta biyaha." },
          { q: "Sidee lagu ilaalin karaa biyaha lagu isticmaalo guryaha ?", a: "in la xero tubooyinka marka la isticmaalo." },
          { q: "Waa maxay uumi bax ?", a: "Waa isbedel tartiib ah ee hoor loogu bedelo hawo ama neef." },
          { q: "Waa maxay xareedeyn ?", a: "waa nadiifinta biyaha." },
          { q: "Sheeg sida loogu soo saari karo cusbo biyaha badda ?", a: "habka uumi baxa iyo habka karkarinta biyaha." },
          { q: "Immisa cusbo ah ayaa ku jirto halkii liitar oo biyaha badda ah ?", a: "494 garaam" },
          { q: "Maxaa la samenayaa hadii la rabo si degdeg ah cusbo in loogu soo saaro biyaha badda?", a: "Waxaa la adeegsanaa habka karkarinta." },
          { q: "Sheeg goobaha aadka loogu isticmaalo biyaha ?", a: "Guryaha , beeraha iyo warshadaha" },
          { q: "Maxaa lagu sameyaa biyaha guryaha lagu isticmaalo ?", a: "waxaa loo adeegsadaa cunto Karin , cabid , qubeys , dhaqida iyo waraabinta beeraha" },
          { q: "Maxaa lagu sameyaa biyaha laga isticmaalo beeraha ?", a: "waraabinta dalaga beeraha , dhaqida miraha iyo qasida suntan cayayaanta." },
          { q: "Sheeg warshadaha aadka u isticmaala biyaha ?", a: "Kuwa soo saaro warqadaha , birta , kiimikada , iyo kuwa kale." }
        ]
      }
    ]
  },
  {
    phase: 2,
    name: "Phase 2 (Cutubka 3aad & 4aad)",
    chapters: [
      {
        title: "Cutubka 3aad : Habdhiska taranka",
        questions: [
          { q: "Waa maxay naasley ?", a: "Waa xayawaan kasta oo laf dhabarrey ah oo dhiig kulul leh dhadigoodna leh naaso soo saaro caano." },
          { q: "Sheeg tusaale kamid ah naasleyda ?", a: "Lo’da , ariga , geela , libaaxa" },
          { q: "Waa maxay taran ?", a: "Taranku waa astaan ka mid ah astaamaha noolaha" },
          { q: "Waa maxay feromoon ?", a: "Feramoon waa fariin side kiimikaaleed oo laga soo deeyo qanjirka jirka" },
          { q: "Waa maxay bacrimin ?", a: "Bacrimin waa marka isu galmooodaan labka iyo dheddiga oo ay midoobaan shahwada iyo ugxaanta" },
          { q: "Waa maxay uur-ku sidka ?", a: "Uur-ku sidku waa koriinka buuxa ee uurjiik aadamiga" },
          { q: "Waa maxay ilmo galeen ?", a: "Ilmo galeen waa xubin ku dhex taala bartamaha godka sinaha" },
          { q: "Maxay leeyihiin naasleyda ?", a: "Waxa ay leeyihiin lafdhabar iyo dhiig kulul" },
          { q: "Sidee ayay ku tarmaan naasleyda ?", a: "Habka taran jinsiyeedka" },
          { q: "Sheeg xubnaha taranka ee dheddiga naasleyda ?", a: "Laba ugxaan sidayaaal, Laba marin ugxaaneed, Ilmo galeen, iyo Xubinta galmada." },
          { q: "Maxay soo saarayaan xaniinyaha ?", a: "Unugyada taranka ee labka ee lagu magacaabo xawo" },
          { q: "Sheeg xubnaha taranka ee labka naasleyda ?", a: "Laba xaniinyo, Marinka xawada, Tubada saarta xawada, Qanjirka taranka, iyo Xubinta galmada." },
          { q: "Sawirkaan Maxuu muujinaayaa ? (Sawirka bacriminta)", a: "Waxuu muujinaayaa habka ay bacraminta udhacdo" },
          { q: "Yaa iisku xera hooyada iyo uurjiifka ?", a: "waxaa isku xiriiriya madheerta" },
          { q: "Xagee uu ka helaa uurjiifka cuntada ?", a: "Xudunta" },
          { q: "Waa immisa muddada uur sidka ee : bani’aadamka , lo’da , geela , ariga , dooliga ?", a: "Bani’aadamka 9 bilood, Lo’da 9 bilood, Geela 12 bilood, Ariga 5 bilood, Dooliga 24 maalmood." },
          { q: "Sheeg da'da qaangaarka ee wiilasha ?", a: "13-15 sano" },
          { q: "Sheeg saddex kamid ah calaamadaha qaangaarka ee wiilasha ?", a: "Waxaa waynaada xiniinyaha/xubinta galmada, garbaha ayaa balaarta, iyo codka oo isbeddela." },
          { q: "Sheeg da'da qaangaarka ee gabdhaha ?", a: "10-13 sano" },
          { q: "Sheeg saddex kamid ah calaamadaha qaangaarka ee gabdhaha?", a: "Ugxaan sidayaasha oo soo daaya ugxaan, caadada oo timaada, iyo sinaha oo ballaarta." },
          { q: "Goormee ayey caadada kudhacdaa dumarka ?", a: "Waxey kudhacdaa 28ii cisho mar" },
          { q: "Xagee ayuu ku noolyahay rahu ?", a: "Biyaha iyo barriga" },
          { q: "Goormuu tarmaa raha ?", a: "Xilli roobeedka" },
          { q: "Sidee buu ku tarmaa raha ?", a: "Taran jinsiyeed" },
          { q: "Xagee uu ka dhacaa taranka raha ?", a: "Dibada raha" },
          { q: "Waa maxay bacrimin dibadeed ?", a: "Bacrimin dibadeed waa bacrimin ka dhacda dibada jirka" },
          { q: "Muxuu dhalaa raha ?", a: "Ukun" },
          { q: "Maxay u baahantahay ugxaanta raha ?", a: "Qoyaan iyo biyo" },
          { q: "Maxaa ku wareegsan ugxaanta raha ?", a: "Xab isjiidjiiddanaayo" },
          { q: "Muxuu la qayliyaa raha labka ah xilliga roobka ?", a: "Si uu usoo jiito dheddiga" },
          { q: "Sheeg waxtarka uu leeyahay xabka ku wareegsan ugxaanta raha ?", a: "Waxa uu ka caawiyaa ugxaanta in ay isku dhegto iyo in ay biyo qaadaan" },
          { q: "Xagee ka neefsataa kaluumada ?", a: "Waafiyadood" },
          { q: "Waa maxay kaluun ?", a: "Kaluun waa xayawaan lafdhabareey ah oo dhiig qabow leh" },
          { q: "Xagee ayuu ku noolyahay kaluunka ?", a: "Biyaha" },
          { q: "Maxun dhalaa kaluunka ?", a: "Ukun" },
          { q: "Sheeg noocyada kaluunka ?", a: "Daanlaawe, Lafley, iyo Carjawlay" },
          { q: "Waa maxay daanlaawe ?", a: "Waa kaluun afkiisa furanyahay oo aan lahayn wax daan ah" },
          { q: "Waa maxay laflayda ?", a: "Waa kaluun leh qalfoof kasameysan laf" },
          { q: "Waa maxay carjawleyda ?", a: "Waa kaluun leh qolfoof kasameysan carjaw ama tahar" },
          { q: "Sidee buu ku tarmaa kaluunka ?", a: "Taran jinsi dibadeed ah" },
          { q: "Sheeg farqiga u dhaxeeyo kaluunka lafleyda ah iyo kan carjawga ah ?", a: "Lafleydu waxay leedahay lafo adag, carjawleyduna waxay leedahay lafo jilicsan." },
          { q: "Xagee buu ku tarmaa kaluunka ?", a: "Biyaha dhexdood" },
          { q: "Ma daryeelaa kaluunka ubadkiisa ?", a: "Maya" },
          { q: "Waa kuma kaluunka xanaaneeya ubadkiisa ?", a: "Tilaabiye" },
          { q: "Xagee buu ku qaadaa tilaabiye ubadkiisa ?", a: "Waxuu ku qaadaa Afkiisa" },
          { q: "Tusaale ka bixi mid kasto ka mid ah noocyada kaluunka ?", a: "Daanlaawe (kaluunka daanlaawe), Lafleyda (lambarey toonada), Carjawda (libaax badeed)." },
          { q: "Waa maxay shimbir ?", a: "Shimbir waa xayawaan lafdhabareey ah oo intooda badan duula waxayn aleeyihiin dhing kulul" },
          { q: "Maxay dhalaan shimbiruhu ?", a: "Ukumo" },
          { q: "Xagee ay ku dhalaan shimbiruhu ?", a: "Buulaha" },
          { q: "Ma leeyihiin shimbiraha xubno taran oo dibada yaala ?", a: "Maya" },
          { q: "Maxaa loo yaqaanaa shimbiraha marka ay ku fadhiyaan ukumahooda ?", a: "Cuq ama xafashto" },
          { q: "Sheeg waxtarka uu leeyahay huurinta ukumaha ?", a: "Iney helaan heer kul ku habboon" },
          { q: "Waa maxay ukun dillaacan ?", a: "Waa muddada ay shimbirtu ku dul fadhido ukunta" },
          { q: "Ma isku mid baa muddada ukun dilaacinta ee shimbiraha ?", a: "Maya" },
          { q: "Sheeg mudada ukun dilaacinta digaag ( doorada) ?", a: "Ukun dilaacinta digaaga waa 21 cisho" },
          { q: "Sheeg hababka ukun dilaacinta shimbiraha ?", a: "Digaaga oo ku dul fadhiisata ukunta ama makiinada ukun dilaaciyaha." },
          { q: "Waa maxay ukun dilaaciye ?", a: "Waa makiinad ukunta diirimaad siisa" },
          { q: "Ma xanaaneeyaan shimbiruhu ubadkooda?", a: "Haa" },
          { q: "Sidee ayay ku tarmaan shimbiruhu?", a: "Taran jinsiyeed" }
        ]
      },
      {
        title: "Cutubka 4aad : Dhirta",
        questions: [
          { q: "Waa maxay footoosintasiska ?", a: "Waa hanaanka ay dhirtu ku sameysato cuntadeeda." },
          { q: "Sheeg qaybaha uu ka koobanyahay footoosintasiska ?", a: "Photo iyo synthesis" },
          { q: "Waa maxay micnaha photo - synthesis ?", a: "Photo = ilays, Synthesis = sameyn" },
          { q: "Xaguu ka dhacaa shaqada footo sintesiska ?", a: "Caleenta geedka." },
          { q: "Si uu footosintesiska udhaco maxaa laga maar maan ah in uu geedka helo ?", a: "Karboon labo ogsaydh, Biyo, Ilayska qoraxda, iyo Maadada cagaarisada." },
          { q: "Maxaa lagu magacaabaa daloolaha caleenta ?", a: "waxaa lagu magacaabaa ibo." },
          { q: "Waa maxay (Chloropyl) ama cagaariso ?", a: "Waa maadada caleenta u yeesha midibka cagaaran." },
          { q: "Maxay soo saartaa caleenta ?", a: "Gulukoos iyo oksajiin." },
          { q: "Cuntada uu geedka sameeyo halkee lagu kaydiyaa ?", a: "Jarida geedka , Xididada , Miraha" },
          { q: "Xagee laga helaa tamarta ?", a: "Cuntada" },
          { q: "Waa maxay sil silada Cuntada ?", a: "Waa xariirka isku tiirsanaanta ah ee Cuntada ka dhexeeya dhirta iyo Xayawaanada" },
          { q: "Maxaa dhacaya hadii silsilada cuntada mid ka mid ah maqanyahay ? Waayo ?", a: "Waxaa dhacaya isku tiirsanaan la'aan, waayo midba midka kale wuu ku tiirsan yahay." },
          { q: "Soo baar wasa loola jeedo shabakada Cuntada ?", a: "Waa xeriirka kadhaxeeya hanaanka tamar socodka" },
          { q: "Sheeg dhirta iyo Xayawaanada waxa ay ku kala duwan yihiin ?", a: "Dhirta masocoto, cuntadooda ayey sameystaan, koritaankoodu ma xadidna; Xayawaanka wuu socdaa, cuntada ma sameysto, koritaanku wuu xadidan yahay." },
          { q: "Sharaxaad kooban ka bixi isku tiirnaanshaha dhirta iyo Xayawaanada ?", a: "Dhirta waxay xayawaanka ka heshaa kaarboon labo ogsaydh, xayawaankuna wuxuu dhirta ka helaa oksijiin, cunto iyo daawo." },
          { q: "Si kooban usharax waxa dhici karo nolosha Xayawaanada hadii laga jaro dhirta ama ay yaraato ?", a: "Waxaa ku dhici doona hooy la'aan, Cunto la'aan iyo ogsijiin la'aan." },
          { q: "Keen tusaale ku saabsan sil silada Cuntada ?", a: "Cowska -> Ayaxa -> Raha -> Maska -> Gorgan." },
          { q: "Waa maxay soo saare ?", a: "Waa dhirta" },
          { q: "Waa maxay dheefsadaha 2aad ?", a: "Waa xayawaanada cuna dhirta." },
          { q: "Maxay dhirtu ka heshaa xayawaanada?", a: "Kaarboon laba oksaydh." },
          { q: "Maxay xayawaanada ka helaan dhirta?", a: "Cunto iyo oksajiin" },
          { q: "Yaa ka caawiya dhirta falxida?", a: "Xayawaanada." },
          { q: "Maxay qabtaan xidida geedka?", a: "Waa halka ay dhirtu biyaha ka soo nuugto" },
          { q: "Sheeg noocyada quudashada xayawaanada ?", a: "Dhir cune, Hilib cune, iyo Dhir iyo hilib cune." }
        ]
      }
    ]
  },
  {
    phase: 3,
    name: "Phase 3 (Cutubka 5aad & 6aad)",
    chapters: [
      {
        title: "Cutubka 5aad : Cimilo gooreed",
        questions: [
          { q: "Sheeg farqiga u dhaxeeya cimilo iyo cimilo gooreed?", a: "Cimilo waa xaaladaha gibilka ee meeli leedahay muddo dheer, cimilo gooreeduna waa muddo gaaban." },
          { q: "Maxaa lagu magacaabaa barashada cimilada?", a: "meteorology (meetoroloji)." },
          { q: "Maxaa loo yaqaanaa saynisyahanka ka shaqeeya cimilada?", a: "Cimilo aqooneed." },
          { q: "Maxaa lagu uruuriyaa xogaha cimilo gooreedyada?", a: "dayax gacmeedyada iyo kobmiyuutarada." },
          { q: "Sheeg qalabyada lagu cabiro cimilo gooreedka cabirkooda ?", a: "Xawaare beegga (dabaysha), Roob-beegga (roobka), Huur-beegga (qooqaanka/uumiga), Kulbeegga (heerkulka), Cadaadis beegga (cadaadiska hawada)." },
          { q: "Maxaa sababaya in labarto cimilada?", a: "is bedellada cimilada oo sameyn ku leh aadanaha dunidaan ku nool." },
          { q: "Sheeg cimilada ugu saameynta badan ?", a: "Heer kulka, Xadiga roobka da'a, iyo Dabaysha." },
          { q: "Waa maxay tacabka beeraha ?", a: "beerida dhirta." },
          { q: "Waa maxay keymo ?", a: "waa keyd dabiici ah oo illaahay nasiiyay." },
          { q: "Waa maxay dalxiis ?", a: "dalxiisku waa u safrida goobo leh dhaqamo." },
          { q: "Waa maxay safaanaa ?", a: "Safaanaa waxaa loo yaqanaa cowska dhaadheer." },
          { q: "Immisa aye gaarayaan geedaha ka baxa keymaha ?", a: "3 Tiriliyan oo geed ah." },
          { q: "Maxay leeyihiin goobaha loo dalxiis tago ?", a: "Ilbaxnimo iyo waayo aragnino." },
          { q: "Sheeg cimilo goboleedyada leeyihiin keymaha ?", a: "cimilo kuleyl, cimilo dhexdhexaad, iyo Cimilo qabow." }
        ]
      },
      {
        title: "Cutubka 6aad : Fududaynta Hawsha",
        questions: [
          { q: "Waa maxay hawl ?", a: "Hawl waa wax laqabtay marka xoog la adeegsado si walax looga dhaqaajiyo meel loona geeyo meel kale." },
          { q: "Waa maxay Tamar ?", a: "Tamartu waa awoodda hawl lagu qabto." },
          { q: "Sheeg labada nooc ee ugu waa weyn ay tamartu leedahay ?", a: "Waa tamarta socodka iyo tamarta kaydsan." },
          { q: "Waa maxay mashiinada fudud ?", a: "Mashiinada fudud waa: qalabyada howsha fududeeya." },
          { q: "Labo ka sheeg mashiinnada fudud shaqooyinka u gaarka ah oo ay qabtaan ?", a: "Xoogga ayey ka gudbiyaan meel una geeyaan meel kale, waxayna yareeyaan waqtiga hawsha." },
          { q: "Immisa qaybood ayaa loo qaybiyaa mashiinada fudud?", a: "Lix qaybood: Garaangar, sabarad, Kabaalka, Salax janjeera, Kariirad, Musbaarka maraaraha, iyo Khaafiyad." },
          { q: "Waa maxay sallax janjeera?", a: "Salllax janjeera waa dul janjeer leh kana sameysan alwaax ama bir fidsan." },
          { q: "Maxaa loo adeegsadaa sallax janjeera?", a: "waxaa loo adeegsadaa fududeynta walxaha culus si loo gaarsiyo meel sare." },
          { q: "Yaa adeegsada sallax janjeera?", a: "sallax janjeera waa inta badan adeegsada dadka baahiyaha gaarka qaba oo aan socon Karin." },
          { q: "Sheeg noocyada sallax janjeer?", a: "noocyada sallax janjeera waxaa kamid ah: Musbaarka maraaraha leh." },
          { q: "Maraaran maxaa loo adeegsadaa?", a: "In lagu dhuujiyo walxaha, in la isku xiro biraha, in lagu dalooliyo biraha, iyo in kor loogu qaado walxaha culus." },
          { q: "Waa maxay kariirad?", a: "Kariirad: waa laba sallax janjeera oo kala daadagaya." },
          { q: "Maxaa loo adeegsadaa kariiad?", a: "Kala qaybinta walxaha, kala jaridda walxaha, iyo lagu kala dilaaciyaa walxaha." },
          { q: "Waa maxay kabaal?", a: "Kabaalka waa ul fidsan oo ka sameysan loox ama bir adag oo ku dul wareegta bar ama taako." },
          { q: "Maxaa loo adeegsaadaa kabaalka?", a: "Waxaa loo adeegsadaa qaadida iyo dhaqaajinta walxaha culus." },
          { q: "Sheeg kabaalka waxa uu ka kooban yahay?", a: "Sabarad (dusha fidsan), Taako/barkin (barta dhexe), Karti taag (xoogga), iyo Rarka (culayska)." },
          { q: "Sheeg qaacidada lagu helo hawl iyo waxa lagu halbeega?", a: "H = X x F (Hawl = Xoog x Fogaan)." },
          { q: "Maxaa lagaga soo gaabiyay ereyada H = XF ?", a: "H = hawl , X = xoogg , F = fogaan." },
          { q: "Sheeg Halbeega lagu cabbiraa Fogaan, Xoog iyo Hawl ?", a: "Fogaan = Mitir (M), Xoog = Niyuutan (N), Hawl = Juul (Joules)." },
          { q: "Raadi hawsha la qabtay haddi xoogg dhan 30N oo uu dhaqaajiyay 10m oo fogaan ah?", a: "300 J (Juul)" },
          { q: "Waa maxay sabarad?", a: "Sabarad wa dusha fidsan oo ka sameysan bir ama alwaax." },
          { q: "Sahra ayaa dhulka sare uga qaadday digsi bariis kujira oo 5kg ah, waxa ayna saartay miis jooggiisu yahay 2 mitir, hadaba soo saar hawsha la qabtay? (G = 10m/s^2)", a: "40 J (Juul) (Furfuris: X = M x G = 10kg/20N, H = 20N x 2m = 40 J)" },
          { q: "Waa maxay khafiyadu?", a: "Khafiyadu waa garaangar jeexdin leh." },
          { q: "Waa maxay muhiimada ama ulajeeda loo isticmaalo cajaladdu?", a: "cajaladdu waxay fududeysaa hawlaha si loo kaydsado tamarta ama loo adeegsado xoog aad u yar." },
          { q: "Sheeg noocyada khafiyadaha?", a: "Mid Aan dhaqaaqin iyo Mid dhaqdhaqaaqda." },
          { q: "Sheeg tusaalooyinka khafiyadaha?", a: "Wiishashka, Culeys qaadayaasha kaar glift, Garan garta ceelasha biyaha cajaladda, iyo Qalabyada jirdhiska." }
        ]
      }
    ]
  },
  {
    phase: 4,
    name: "Phase 4 (Cutubka 7aad & 8aad)",
    chapters: [
      {
        title: "Cutubka 7aad : Ilayska",
        questions: [
          { q: "Waxaa maxay kaamirada biin daloolka ?", a: "waa kaamire sahlan oo bikaaco la aan ah hasayeeshee waxaa ay leedahay dalool yar oo xakameeya ilayska." },
          { q: "Maxay ka sameysan tahay kamiirada biin daloolka ?", a: "sanduuq aan ilaysku gudbin oo dhinac ka leh dalool yar oo ilaysku ka soo galo." },
          { q: "Maxaa sameysaa kaamirada biin daloolka ?", a: "Kaamirada biin-daloolka waxay sameysaa humaag foorara / Rogan / Qaliban." },
          { q: "Maxaa dhacaya marka ilaysku uu ka yimaado cirifka sare ee geedka ?", a: "waxa uu ku dhacayaa halka hoose ee filimka ama waraaqada cad ee bin daloolka kaamirada." },
          { q: "Maxaa dhacaya marka ilaysku uu ka yimaado salka hoose ee geedka ?", a: "Tani waxa ay keeneysaa oo ay sababeysaa in sawirka geedku uu fooraaro." },
          { q: "Qaabkee u sameysan tahay ishu ?", a: "ishu waxa ay u samaysan tay qaabka ukunta." },
          { q: "Ishu maxay sameysaa ?", a: "Ishu waxa ay samaysaa humaag foorara haseyeeshee maskaxda ayaa toosisa oo saxda." },
          { q: "Tax shanta qayb ay ishu ka kooban tahay ?", a: "Xuubka isha, Bikaaca isha, Bu'da isha, Retinaha isha, iyo Wiilka isha." },
          { q: "Sawirka isha aadanaha maxaa kamid ah qaybaheeda ?", a: "Xuubka, Wiilka, Bikaacda, Bu'da, Muruqyada, Retinaha, iyo Xididka dareenka." },
          { q: "Waa maxay xuubka isha ?", a: "Xuubka isha waa lakabka sare ee isha, waana if-gudbiye si fududna u gudbiya ilayska." },
          { q: "Sheeg shaqada xuubka isha ?", a: "in ay ilayska u ogolaato inuu u gudbo gudaha isha." },
          { q: "Waa maxay bu'da isha ?", a: "Bu'da isha waa qaybta go'aamisa midibka isha." },
          { q: "Sheeg shaqada bu'da isha ?", a: "Waxa ayna xakameysa xaddiga ilayska ee galay wiilka isha iyadoo kala baxda marka uu ilaysku yar yahay." },
          { q: "Waa maxay wiilka isha ?", a: "waa barta yare ee wareegsan ee dhex bartanka bu'da isha." },
          { q: "Sheeg shaqada wiilka isha ?", a: "shaqadeedu waa in ay ilayska usii gudbiso bikaacada isha." },
          { q: "Waa maxay bikaacada isha ?", a: "Bikaacada isha waa bikaacada aan u adkeyn sida midda kaamirada." },
          { q: "Sheeg shaqada bikaacada isha ?", a: "in ay ilaysku iskugu soo uruuriso barta retinaha ee isha." },
          { q: "Sharaxaad kooban ka bixi arag dheerida ?", a: "Arag dheerida waa in aan la arkin waxa kaa fog, waxaana sabab u ah in humaaga uu ka sameysmo retinaha gadaashiisa." },
          { q: "Sharaxaad kooban ka bixi arag gaabnida ?", a: "Arag-gaabnida waa in aan la'arkin waxa kuu dhow, waxaana sabab u ah in humaaggu ka samaysmo retinaha hortiisa." },
          { q: "Maxaa lagu saxaa arag dheeridu ?", a: "waa lagu saxaa bikaaco kulmiso ah." },
          { q: "Maxaa lagu saxaa arag gaabnida ?", a: "waxaa lagu saxaa bikaaco ilays firdhiye ah." },
          { q: "Is barbardhig isha iyo kaamirada bin-daloolka ?", a: "Labaduba waxay soo saaraan sawir foorara, laakiin isha maskaxda ayaa toosisa, halka kaamirada aysan lahayn wax toosiya." }
        ]
      },
      {
        title: "Cutubka 8aad : Dhulka iyo Hawada Sare",
        questions: [
          { q: "Waa maxay urur xiddigeedka ?", a: "koox xiddigo ah oo habeenkii cirka lagu arko, lehna xuduud go'an." },
          { q: "Sheeg macnaha erayga urso ?", a: "Jurso waa magic laatiin ah oo loo yaqaano oorsa ah (ursus/bear)." },
          { q: "Sheeg macaga labaad ee loo yaqaano xiddigga cirifka ?", a: "Xiddigga Qiblada." },
          { q: "Side ayaa xiddigta cirifku ucaawisaa badmaaxayada ?", a: "cirifeedku wuxuu caawiyaa bad mareenka mar walbana wuxuu joogaa meel isku mid ah oo waqooyi ah." },
          { q: "Sheeg qaar kamid ah Urur Xiddigeedyada ?", a: "Xiddigga cirifka, Nin la gigay, Xiddigga libaaxa, Todobka, iyo Isku tallaabta koonfureed." },
          { q: "Urur xiddigeedka xagge laga arki karaa ?", a: "cirifka waqooyi iyo cirifka koofureedka." },
          { q: "Waa maxay macnaha erayga leo ?", a: "Leo waa eray Giriig oo ah macnihiisu yahay libaax." },
          { q: "Bilaha sanadka, kuwee ayaa la arkaa urur xiddigeedks laxaha ?", a: "bisha Oktoobar." },
          { q: "Waa maxay urur xiddigeeda isku tallaabta koonfureed ?", a: "kuwa adka ee caawiya bad mareenada u socdaala koonfurta." },
          { q: "Imisa xiddiga ayuu ka kooban yihiin urur xiddigeedyadan (isku tallaabta koonfureed) ?", a: "waa urur xiddigeed ka kooban shan xiddigood." },
          { q: "Waa mxay dayax gacmeedku ?", a: "dayax, meere ama mashiino ku wareegga meere ama xiddig." },
          { q: "Waa maxay qaybaha dayax gacmeedka ?", a: "Anteenno iyo Il Tamareed." },
          { q: "Maxaa loogu faa'ideysan karaa isticmaalka dayax gacmeedka?", a: "isgarsiinta , cilmi barista , Saadaalinta cimilo gooreedka iwm." }
        ]
      }
    ]
  },
  {
    phase: 5,
    name: "Phase 5 (Cutubka 9aad & 10aad)",
    chapters: [
      {
        title: "Cutubka 9aad : Tamarta Kulka",
        questions: [
          { q: "Maxay tahay qorraxdu ?", a: "qorraxdu waa isha asaasiga ah ee laga helo kul tamareedka." },
          { q: "Waa maxay kul ?", a: "Kulku waxa uu yahay nooc kamid ah tamarta oo muhiim u ah nolosha, lagana helo qorraxda." },
          { q: "Maxay tahay ilaalinta tamarta kulka ?", a: "ilaalinta tamarta kulka waa habsami u adeegsiga tamarta la haysto iyada oo la ilaalinayo Tamar lumidda." },
          { q: "Sidee kulka loo kaydin karaa ?", a: "habab kala duwan sida in la isticmaalo Soolarada, Tannuusyada iyo Kululeysada IWM." },
          { q: "Sheeg qaybaha burjikooyinka ?", a: "Burikooyinka waxaa loo qeybiyaa saddex nooc: Burjiko xadiid, Burjiko dhoobo, Burjiko casri ah." },
          { q: "Burjiko xadiidku maxay kasameysan tay ?", a: "dhinacyadeedu iyo godkeeduba waxay kasameysan yihiin Xadiid." },
          { q: "Sheeg farqiqa u dhaxeeya burjikada casriga ah iyo tii hore looga isticmaali jiray dalka?", a: "burjikada casriga ah waa mid aan dhuxul badan isticmaalin, halka middii hore ay dhuxul badan isticmaasho." }
        ]
      },
      {
        title: "Cutubka 10aad : Deegaanka",
        questions: [
          { q: "Waa maxay dikhowga carrada ?", a: "dikowe carrada waa wasakhaynta carrada." },
          { q: "Carradu maxay muhimu tahay ?", a: "Carradu waxa ay muhim u tahay jiritaanka dhirta iyo beeraha." },
          { q: "Sheeg labo wax yaabood oo keena dikhowga carrada ?", a: "Qashinka ka dhasha howlaha aadanaha iyo qaslunka u dhasha si dabiiciga ah." },
          { q: "Sheeg seddax ka mid ah qashinka ka dhasha howlaha aadanaha ?", a: "Sunta haraaga warshadaha, Kaydinta wasakhda ee godadka khashinka, iyo Howlaha dhismaha guryaha iyo wadooyinka." },
          { q: "Sheeg seddax ka mid ah qashinka ka dhasha si dabiiciga ah ?", a: "Foolkaanooyinka (qarax dhulka hoostiisa), Dhul gariirka, iyo Fatahaadaha (webiyada/baraf dhalaalay)." },
          { q: "Maxaa keena foolkaanada ?", a: "marka ay aad u kululaato macdanta ku jirta dhulka." },
          { q: "Labo ka sheeg waxtarka dhirta ay leedahay ?", a: "Dhirtu waxay deegaanka ka ilaalisaa dhiikhawga, waxayna hoos u dhigtaa heer kulka xilliga jiilaalka." },
          { q: "Saddex kasheeg habaka kala duwan ée dhirta lagu daryeelo ?", a: "La dagaalanka xaalufinta dhirta, Beerida dhir cusub, iyo Bacriminta dhirta." },
          { q: "Waa maxay dhirayn ?", a: "Dhirayntu waa in dhir cusub lagu tallaalo iyada oo la samaynayo kaymo cusub." },
          { q: "Waa maxay daryeelka biyaha ?", a: "Daryeelka biyuhu waa dhowridda iyo maareynta biyaha iyo khayraadkooda." }
        ]
      }
    ]
  },
  {
    phase: 6,
    name: "Phase 6 (Cutubka 11aad & 12aad)",
    chapters: [
      {
        title: "Cutubka 11aad : Danabka iyo Birlabnimada",
        questions: [
          { q: "Waa maxay birlab ?", a: "Birlabku waa bir awood u leh in ay soo jiidato biraha kale." },
          { q: "Xagee ayay ka bilaabatay soo saarista birlabta ?", a: "magaalo yar oo Turkida ku dhaw loo yaqaano Magnesia." },
          { q: "Goormee ayuu sameyay seynisyahan orestid tijaabadaan ?", a: "1820kii" },
          { q: "Sheeg noocyada birlabta mid walbane qeex ?", a: "Birlab rasmi ah (birlabnimada heysa muddo dheer), Birlab aan rasmi ahayn (lumiya muddo kooban), iyo Birlab danabeed (ku xiran danabka)." },
          { q: "Waa maxay bedka birlabta ?", a: "waa goobta ku wareegsan birlabta ama danabka taas oo laga dareemo xooga birlabta." },
          { q: "Xagee xooga birlabta ku badan yahay ?", a: "Cirifyada birlabta." },
          { q: "Sheeg sharciga aasaaska ah ee birlabta ?", a: "Cirifyada isku midka ah ee birlabtu way kala caraaraan, cirifyada kala duwan way isasoo jiitaan." },
          { q: "Immisa cirif ayay leedahay birlabtu ?", a: "Birlabtu waxa ay leedahay laba cirifood oo kala ah : Cirifka waqooyi iyo Cirifka koonfureed." },
          { q: "Maxaa loo adeegsadaa hard darive ?", a: "waxaa loo adeegsadaa in lagu keydiyo xogaha sida e-mailada , sawirada iyo aflaanta." },
          { q: "Sheeg qayb kamid ah adeegsiga birlabta?", a: "dawan-danabeedka iyo matoor danabeedka." },
          { q: "Maxaa loo adeegsan karaa Birlab-danabeedka?", a: "wiishaska kala saaro birta xadridka, iyo dhaqaajinta walxaha culus." },
          { q: "Waa maxay matoor danabeed ?", a: "matoor danabeed waa qalab loo adeegsado tamarta korontada in uu u bedelo tamarta socodka." },
          { q: "Birta maxaa laga dhalin karaa ?", a: "Birlabta danab ayaa laga dhalin karaa si islamar kaana waxay dhalineysa danabka birlab ah." },
          { q: "Birlab danabeedku xaggee bey ka dhalataa?", a: "waxa ay ka dhashataa maayada danabka, waxayna leedahay adeegsi badan sida wishka, codbaahiyaasha iyo sameecada." },
          { q: "Maxay tahay ujeedada ah in lasameeyo tijaabada ah in fiilada lagu duubo musbaarka kadibana lagu xiro fiilada labada qotan ee batariga ?", a: "In laga dhaliyo birlab danabeed." },
          { q: "Matoor danabka muxuu badalaa?", a: "waxa uu u beddela tamarta danabka tamarta socodka." },
          { q: "Sheeg qaybaha matoorada sahlan uu leeyahay?", a: "Armajar (daynabo), Tirtire, Bed-birlabeed, Komiyuutaytar, Gobal bir ah, iyo Quwad DC ah." },
          { q: "Sidee ayuu u shaqeeyaa matoor danabeedka?", a: "Waa qalab loo adeegsado tamarta korontada in uu ubeddelo tamarta socodka, waxaa laga helaa guryaha iyo xafiisyada." },
          { q: "Sheeg qeybaha dawanada ?", a: "Dawan gacmeed iyo Dawan danabeed." },
          { q: "Waa maxay dawaan danabeedka?", a: "Waa qalab makaanika ah oo uu ku shaqeeyo birlab-danabeed, wuxuuna soo saaraa dhawaaqyo isku xigxiga." },
          { q: "Waa maxay micnaha laga wado dawan-gacmeed?", a: "dawan-gacmeed waxaa waaye micnahiisu ganbaleel." }
        ]
      },
      {
        title: "Cutubka 12aad : Dhaqashada Xoolaha",
        questions: [
          { q: "Waa maxay digaaggu ?", a: "xayawaanka ugu badan uguna ballaaran ee dabjoogga loo yaqano, shimbir baalal leh oo aan duulin lagana helo ukun/hilib." },
          { q: "Sheeg hababka loo dhaqan karo digaagga ?", a: "Habka dibad joogga, Habka xero leh dhaqdhaqaaq xor ah, iyo Habka xero aan lahayn dhaqdhaqaaq xor ah." },
          { q: "Maxaa dhacaya haddii heer kulka hawada ee xerada digaagga ukunta uu hoos uga dhaco 22C?", a: "waxaa dhacda inay badato cunto cunidda digaagga." },
          { q: "Habkee ugu fudud hababka loo dhaqdo digaagga ?", a: "waxaa ugu fudud habka dibad joogga." },
          { q: "Sheeg laba kamid ah faa'iidooyinka ay leeyihiin habka xero ku haynta digaagga ?", a: "Waxaa fudud dhaqashadooda iyo la socodka, waxaana laga helaa saxarro digaag oo beeraha loo adeegsado." },
          { q: "Hadii digaaggii lagu haayo xerooyinka aan lahayn dhaqdhaqaaq xor ah maxaa ka dhalan karo ?", a: "waxaa soo kordha cudurro cusub oo ku dhaca digaagga oo ay keentay dhaqdhaqaaq la'aanta." },
          { q: "Sheeg noocyada dhaqashada digaagga iyo ujeedooyinka loo dhaqdo nooc walba ?", a: "Hilboolayaal (laga helo hilib) iyo Ukun dhalayaal (laga helo ukun)." },
          { q: "Sheeg astaamaha lagu garan karo digaagada loo dhaqdo in laga helo hilib ?", a: "In aysan si dhaqsi ah u qaangaarin, iyo in wax soo saarka ukuntooda uu yaryahay." },
          { q: "Noocaan loo yaqaano hilboolayaasha qofka dhaqanayo waxa uu ku quudiyaa cunto nafaqo leh, hadaba sheeg sababta uu u siinaayo ?", a: "waxaa uu u siyaa si uu ugu koro si fiican." },
          { q: "Digaaga loo dhaqdo hilibka dhaqsi miyey ku qaan gaaraan ?", a: "Waa maya." },
          { q: "Sheeg astaamaha lagu garan karo digaagada loo dhaqdo in laga helo ukun ?", a: "In ay xajmi yar yihiin, culayskoodu fudud yahay, iyo in ay dhalaan ukun badan." },
          { q: "Maxay ku xirantahay tirade ukunta digaagga ?", a: "Waqtiga boojaashu bilowday ukunta (da'da qaangaarka), Habka dhagashada (sare ama hoose), iyo Sinjiga digaagga." },
          { q: "Imise ukun ayaa laga rabaa in ay digaagadu ay dhasho sanadkii ?", a: "waa in ay digaaggadu dhashaa 300 oo ukun ah." },
          { q: "Waa maxay xero digaag ?", a: "xero digaag waa guri yar ama la waynayn karo oo si nabad gelyo ah ay digaaggu ugu noolaan karaan." },
          { q: "Guriga ama xerada digaagga waa in ay lahaataa oo laga heli karaa hadaba sheeg seddax kamid ah ?", a: "Hawa wanaagsan/heer kul ku habboon, Dhismo ku filan, iyo Weel cunada loogu shubo." },
          { q: "Waa maxay ujeedada digaagga loogu samaynaayo xero iyo guri ?", a: "waa in laga difaacaa cimilada xun, kulaylka, qabowga, dabaysha iyo ugaarsatada." },
          { q: "Sheeg laba kamid ah astaamaha xerada digaagga ?", a: "Sagxadda/gidaarrada oo adag, iyo in si sahlan looga xaaqi karo saxarrda." },
          { q: "Waa maxay huurin ?", a: "marka ay digaagadda cuqda ahi ku fariisato ukumaheeda." },
          { q: "Sheeg qaybaha huurinta ?", a: "Huurinta dabiiciga ah iyo Huurinta aaladeed." },
          { q: "Qeex huurinta dabiiciga ukunta ?", a: "waa marka ay digaagadda cuqda ahi ku fariisato ukumaheeda." },
          { q: "Qeex midda aalladda ?", a: "ay tahay in ukunta la dhex dhigo mashiin la yiraahdo dilaaciye." },
          { q: "Sheeg shuruudaha lagama maarmaanka u ah huurinta aaladeed ?", a: "Ukunta oo bacrimisan, habka loo kaydiyay, miisaanka, tayada qolofta, hiddesidaha, cudur la'aanta, heerkulka/uumiga mashiinka." },
          { q: "Waa maxay Huunyo ?", a: "huunyo waa cayayaan aad u yar oo dhererkeedu gaarayo ilaa 1-6mm." },
          { q: "Gooryaanku xagee ayuu ku noolyahay ?", a: "mindhicirada iyo uurkujirta digaagga." },
          { q: "Maxaa lagu gartaa digaaggadda marka ay cuq tahay ?", a: "ukumo ma dhasho, 21 maalmood bay ku qaadataa, dareentaa wareer, cod gaar ahna way soo saartaa." },
          { q: "Tiri dhammaan cudurada ku dhaca digaagga ?", a: "Niyuu Kastal, Bronkiitada, Daacuunka, Tiifowga digaagga, iyo Asbergilosiska." },
          { q: "Sheeg habka ugu wanaagsan ee gooryaanka loogu hortagi karo ?", a: "in lagu dadaalo nadaafadda guud ee xereda digaagga." },
          { q: "Sheeg ujeeddada loo dhaqdo digaaggu ?", a: "ujeeddada loo dhaqdo digaaggu waa in laga helo hilib iyo ukun." },
          { q: "Maxaa looga hortegi karaa deris kunoolayaasha ku nool digaagga ?", a: "nadaafad, buufin iyo dawooyin ku habboon." },
          { q: "Sheeg deris ku noolayaasha ugu caansan digaagada ?", a: "Huunyada iyo Gooryaanka." },
          { q: "Hadii 5 digaag midiiba dhasho maalintii hal (1) ukun oo qiimaheedu yahay 5000 Sh.so. Qarasha maalintii laga helaayo waa imisa ?", a: "25,000 Sh.so (5 x 5000 = 25,000)." }
        ]
      }
    ]
  },
  {
    phase: 7,
    name: "Phase 7 (Cutubka 13aad & 14aad)",
    chapters: [
      {
        title: "Cutubka 13aad : Walxaha iyo Astaamahooda",
        questions: [
          { q: "Wan maxay curiye ?", a: "Curiye waa qaabka ugu yar ee ay walaxi u jiri karto." },
          { q: "Muxuu kasameysan yahay curiyaha ?", a: "Hal nooc oo atamyo ah." },
          { q: "Maxay ka kooban yihiin wakax kasta oo innagu xeeran ?", a: "curiyaal." },
          { q: "Waa maxay atam ?", a: "atamku waa walaxda ugu yare ee curiyaha kaas oo weli leh astaamihii kiimikaad ee curiyaha." },
          { q: "Waa maxay tiro atam ?", a: "tirade borotoonnada ee ku jira bu'da atamka curiyaha." },
          { q: "Xagee lagu qoraa tiro atam ?", a: "dhanka hoose ee bidixda sumadda curiyaha." },
          { q: "Waa maxay iskujirka ay ka kooban hawada ?", a: "Naaytaroojiin, Oksijiin, Aargoon iwm." },
          { q: "Immisa curiye ayaa si dabiici ah loo helaa ?", a: "92 kamid ah." },
          { q: "Sheeg curiyaha ugu boqolleyda badan oogada dhulka ?", a: "Oksijiin (46.6%)." },
          { q: "Sheeg sumadda iyo boqolleyda Silikoon ee dhulka ?", a: "Sumadda Si, Boqolleyda 27.7%." },
          { q: "Sheeg sumadaha curiyayaashan: Aluminiyam, Xadiid, Kaalsiyam, Soodiyam, Botaasiyam, Magniisiyam ?", a: "Al, Fe, Ca, Na, K, Mg." },
          { q: "Sheeg tirada ay yihiin curiyaasha ugu caansan ee la isticmaalo ?", a: "Waa 40 curiyaal ah." },
          { q: "Was maxay iskudhis ?", a: "walax ka sameysan labo curiye iyo ka badan oo si kiimikaad isula falgalay." },
          { q: "Iskudhiska uu biyaha kasameysan yahay waa immisa curi ?", a: "Waa labo curi oo kala ah : Haydarojiin iyo Oksijiin." },
          { q: "Waa maxay iskujir ?", a: "isu gaynta labo walxood iyo ka badan, oo aan si kiimikaad isugu xirnayn, welina sita astaamahoodii." },
          { q: "Maxay ka samysan yihiin biyaha badda ?", a: "2 curiye oo kala ah haydaroojiin iyo oksijuin (96% biyo)." },
          { q: "Sheeg iskudhiska biyaha?", a: "haydarojiin iyo oksijiin." }
        ]
      },
      {
        title: "Cutubka 14aad : Habka Cilmibaarista",
        questions: [
          { q: "Waa maxay cilmi baaris ?", a: "hab nidaamsan oo ay isticmaalaan saynisyahanadu si ay u helaan xaqiiqda." },
          { q: "Waa maxay dariq cilmiyeed ?", a: "Dariqadda ay maraan saynisyahanadu marka ay sameynayaan baaritaanka." },
          { q: "Sheeg magaca saynisyahnkii ugu horeeyay ee dariiq cilmiyeed qora iyo xilliga uu noolaa ?", a: "Faransis bakon (Francis Bacon) oo noolaa 1561 dii ilaa 1626dii." },
          { q: "Sheeg shan ka mid ah tilaabooyinka dariiq cilmiyeed ?", a: "in la ogaado mas'alada, in la baaro, in la dejiyo qiyaas, in la fuliyo tijaabo, iyo in la sameeyo falanqeyn." },
          { q: "Tijaabadu maxay u baahantahay ?", a: "in la diyaariyo islamarkaasna la qorsheeyo." },
          { q: "Sheeg seddax qodob oo la tixgeliyo ka hor inta aanan la sameyn tijaabada ?", a: "caddee ujeedada, cadee agabka, iyo in ardaydu dhaqdaan gacmaha tijaabada kadib." },
          { q: "Si loo fuliyo tijaabada maxaa loo baahan yahay ?", a: "Muunad dhir, xayawaan ama kiimiko." },
          { q: "Maxaa ka mid ah xayawaannada nool ee lagu xanaaneeyo qolka sheybaarka ?", a: "Dooliga, bakeylaha, raha iyo diinka." },
          { q: "Sheeg qaar kamid ah agabyada tijaabada ee saynisyahaannadu ay isticmaalaan ?", a: "Qalabka qalliinka xayawaanada iyo qalab wax lagu jarto." }
        ]
      }
    ]
  }
];
